apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2018-03-15T03:45:58Z
  generation: 1
  labels:
    run: kube-demo-app
  name: kube-demo-app
  namespace: default
  resourceVersion: "40854"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/kube-demo-app
  uid: 5f9e6f73-2803-11e8-9329-080027008734
spec:
  replicas: 1
  selector:
    matchLabels:
      run: kube-demo-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: kube-demo-app
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: Always
        name: kube-demo-app
        ports:
        - containerPort: 9093
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2018-03-15T03:45:58Z
    lastUpdateTime: 2018-03-15T03:45:58Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1

